### ISSUE TITLE
OOS Ships spinning like crazy

### ISSUE THREAD

**Issue by Xeneonic** [DeadAirRT/deadairfactions_vro#1]
I'm not sure if it's VRO related for sure. I use no other ship mods than yours, and the other mods I use are not related to jobs either. These two frames were taken maybe 2-3 ticks (oos updates) away from each other. If I'd have to guess, I'd say they're spinning about 5 times per second in random directions, in place at least.

![image](https://user-images.githubusercontent.com/7692702/162137156-94f67685-c48e-4e00-9333-c2bc065560a6.png)

Were they missing some attributes that tells them how fast they're allowed to turn OOS or something like that?

**Comment by Xeneonic** [comment]
I am an idiot, this was supposed to be in https://github.com/DeadAirRT/VRO
I'm sorry. Enemies can also become invulnerable IS if far away enough from the player (Commonwealth faction 20 ships attacking 1 xenon M that didn't die after 5 minutes (icon was shaking so "taking damage" according to the game) and The titan you see on the screenshot here? barely tickled the destroyer and the other way around likewise. I had to go IS after looking at this for a good 30 minutes and saw that the titan was shooting maybe 1 canon at the destroyer and the destroyer maybe 2 at the titan.

Ruined my VRO playthrough so I'm a bit salty over it, but seeing how many moving pieces there are in X4, I can't really fault you for it this early in the expansion. Hell, maybe half of my issues I had were vanilla related and not VRO related...

But I tell you, that titan? Absolute (expletive). A medium vanilla freighter would have dealt more damage.

**Comment by DeadAirRT** [comment]
1) the spinning is a vanilla issue so not sure why you are trying to say anything I have done has changed it

2) the "titan" is from VRO and I don't change it's balance at all.
